"""initial migration

Revision ID: c35308dc15cd
Revises: 766dde9d8519
Create Date: 2025-11-01 13:03:15.711547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c35308dc15cd'
down_revision: Union[str, Sequence[str], None] = '766dde9d8519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('examples', 'explanation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('submissions', sa.Column('status', sa.Enum('ACCEPTED', 'WRONG_ANSWER', 'RUNTIME_ERROR', 'COMPILE_ERROR', name='status_enum'), nullable=False))
    op.drop_column('submissions', 'difficulty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('difficulty', postgresql.ENUM('ACCEPTED', 'WRONG_ANSWER', 'RUNTIME_ERROR', 'COMPILE_ERROR', name='status_enum'), autoincrement=False, nullable=False))
    op.drop_column('submissions', 'status')
    op.alter_column('examples', 'explanation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
